# Generated by Django 4.1 on 2023-04-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ("-publish",)},
        ),
    ]
